default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: security_posts_fetcher

test:
  <<: *default
  database: security_posts_fetcher_test

production:
  <<: *default
  database: security_posts_fetcher
